nodeSelector:
  doks.digitalocean.com/node-pool: pool-ship

webhook:
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-ship

cainjector:
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-ship
